# Generated by Django 4.1.3 on 2022-12-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstaff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriahabitacion',
            table='categoria_habitacion',
        ),
    ]
