# Generated by Django 4.1.3 on 2022-12-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstaff', '0002_alter_categoriahabitacion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='piso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
