# Generated by Django 4.1.3 on 2022-12-10 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstaff', '0003_alter_habitacion_capacidad_alter_habitacion_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='habitacion',
            table='habitacion',
        ),
    ]
