# Generated by Django 4.1.3 on 2022-12-10 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appstaff', '0004_alter_habitacion_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('adultos', models.IntegerField(blank=True, null=True)),
                ('ninios', models.IntegerField(blank=True, default=0, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=150, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appstaff.habitacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reservas',
            },
        ),
    ]
