# Generated by Django 4.1.3 on 2022-12-10 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appstaff', '0005_reservas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reserva',
        ),
    ]
