# Generated by Django 4.1.3 on 2022-12-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstaff', '0006_rename_reservas_reserva_alter_reserva_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appstaff.habitacion'),
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='reservas',
        ),
    ]
