# Generated by Django 4.1.3 on 2022-12-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appstaff', '0007_alter_reserva_room_alter_reserva_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'get_latest_by': ['id']},
        ),
    ]
