# Generated by Django 4.1.3 on 2022-12-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appstaff', '0009_alter_reserva_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='room',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='appstaff.habitacion'),
        ),
    ]
