# Generated by Django 4.1.3 on 2022-12-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstaff', '0010_alter_reserva_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='reserva_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
