# Generated by Django 4.1.5 on 2023-01-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstaff', '0011_reserva_reserva_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='reserva_id',
            new_name='reserva_cod',
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.IntegerField(default=2, help_text='Anulada 0, Confirmada 1, Pendiente 2'),
        ),
    ]
